create table if not exists public.price_items (
  id bigint generated by default as identity primary key,
  category text not null,
  brand text,
  model text not null,
  cash_price numeric,
  card_price numeric,
  sort_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

alter table public.price_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'price_items' and policyname = 'Public read access'
  ) then
    create policy "Public read access"
    on public.price_items
    for select
    using (true);
  end if;
end $$;

create index if not exists price_items_sort_order_idx on public.price_items(sort_order);

insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Intro 24/24', 50000, 59000, 1, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecotec Intro 28/28', 53500, 63200, 2, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Pure 236/7-2', 58000, 68500, 3, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Pure 286/7-2', 61500, 72600, 4, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Pro 236/5-3', 67000, 79100, 5, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Pro 286/5-3', 71000, 83800, 6, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Plus 26 CS/1-5', 82000, 96800, 7, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Plus 32 CS/1-5', 91000, 107400, 8, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Plus 36 CS/1-5', 104000, 122800, 9, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Vaillant', 'ecoTEC Plus 40 CS/1-5', 116800, 137900, 10, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Ademix 24/24', 39000, 46100, 11, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Ademix 28/28', 40500, 47800, 12, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Nitromix 24', 46500, 54900, 13, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Nitromix 28', 50000, 59000, 14, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Nitromix 35', 57000, 67300, 15, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Nitromix Ioni 24', 51500, 60800, 16, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Nitromix Ioni 28', 55000, 64900, 17, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Demirdöküm', 'Nitromix Ioni 35', 62500, 73800, 18, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Protherm', 'Puma Condens 18/24', 40000, 47200, 19, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Protherm', 'Puma Condens 28/28', 41000, 48400, 20, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Protherm', 'Lynx Condens 24', 42500, 50200, 21, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Protherm', 'Lynx Condens 28', 44500, 52600, 22, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Lunatec 24 F', 44000, 52000, 23, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Lunatec 30 F', 47000, 55500, 24, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Lunatec 35 F', 47500, 56100, 25, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Duotec 24 F', 43000, 50800, 26, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Duotec 30 F', 45500, 53700, 27, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Duotec 33', 48500, 57300, 28, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Duotec 42', 53500, 63200, 29, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Duotec 45', 54000, 63800, 30, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'Baykan', 'Duotec 42 DWH', 54500, 64400, 31, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Citius Premix 20', 48000, 56700, 32, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Citius Premix 24', 49000, 57900, 33, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Citius Premix 28', 52500, 62000, 34, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 24', 57000, 67300, 35, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 28', 60500, 71400, 36, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 30', 62500, 73800, 37, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 35', 64500, 76200, 38, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 42', 67000, 79100, 39, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 45', 68000, 80300, 40, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 35 HST', 66000, 77900, 41, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Proteus Premix 45 HST', 70000, 82600, 42, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Cofeo Premix 24', 62000, 73200, 43, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Cofeo Premix 30', 67500, 79700, 44, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Cofeo Premix 35', 70000, 82600, 45, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Kombi', 'ECA', 'Baykan Güneş', 35000, 41300, 46, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Daxom UDAX.12', 29000, 34300, 47, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Daxom UDAX.14', 32000, 37800, 48, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'ECA Phoenix PH 11', 33500, 39600, 49, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Baymak BH 12 LN', 32500, 38400, 50, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Baymak BH 14 LN', 35000, 41300, 51, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Demirdöküm F.11', 34000, 40200, 52, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Demirdöküm F.14', 36000, 42500, 53, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Vaillant MAG 12', 35000, 41300, 54, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Şofben', null, 'Vaillant MAG 14', 36500, 43100, 55, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'Daxom 10 EDM', 37500, 44300, 56, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'Daxom 12 EDM', 38000, 44900, 57, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'Daxom 16 EDM', 41000, 48400, 58, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'Daxom 18 EDM', 42000, 49600, 59, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'ECA Arceus 12 MN TR', 57000, 67300, 60, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'ECA Arceus 15 MN TR', 8500, 10100, 61, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'ECA Arceus 18 MN TR', 62000, 73200, 62, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'ECA Arceus 24 MN TR', 67000, 79100, 63, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Elektrikli Kombi', null, 'ECA Arceus 27 MN TR', 70500, 83200, 64, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Elegant Plus 9.000 BTU', 35000, 41300, 65, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Elegant Plus 12.000 BTU', 38500, 45500, 66, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Elegant Plus 18.000 BTU', 55000, 64900, 67, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Elegant Plus 24.000 BTU', 67000, 79100, 68, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'VAIB 025 Pro 9000 BTU', 37500, 44300, 69, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'VAIB 025 Pro 12000 BTU', 39000, 46100, 70, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'VAIB 025 Pro 18000 BTU', 59000, 69700, 71, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'VAIB 025 Pro 24000 BTU', 75500, 89100, 72, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'climaVAIR Pure 9.000 BTU', 34000, 40200, 73, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'climaVAIR Pure 12.000 BTU', 0, 0, 74, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'climaVAIR Pure 18.000 BTU', 45500, 53700, 75, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'climaVAIR Pure 24.000 BTU', 58000, 68500, 76, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Spaylos Pro 9.000 BTU', 29500, 34900, 77, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Spaylos Pro 12.000 BTU', 30500, 36000, 78, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Spaylos Pro 15.000 BTU', 0, 0, 79, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Spaylos Pro 18.000 BTU', 44500, 52600, 80, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Spaylos Pro 24.000 BTU', 58000, 68500, 81, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Ecotech 9.000 BTU', 30500, 36000, 82, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Ecotech 12.000 BTU', 31500, 37200, 83, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Ecotech 18.000 BTU', 46000, 54300, 84, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Ecotech 24.000 BTU', 60000, 70800, 85, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Niobe 12.000 BTU', 0, 0, 86, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Niobe 18.000 BTU', 0, 0, 87, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Kion 9.000 BTU', 0, 0, 88, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Kion 12.000 BTU', 0, 0, 89, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Kion 18.000 BTU', 0, 0, 90, true);
insert into public.price_items (category, brand, model, cash_price, card_price, sort_order, is_active) values ('Klima', null, 'Kion 24.000 BTU', 0, 0, 91, true);